
-- Создание таблицы для блога
CREATE TABLE IF NOT EXISTS blog_posts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  slug text unique not null,
  image_url text,
  excerpt text,
  content text, -- HTML контент
  is_published boolean default false,
  author_email text,
  views bigint default 0
);

-- Отключение RLS для простоты
ALTER TABLE blog_posts DISABLE ROW LEVEL SECURITY;
