
-- Создание таблицы заказов услуг (сайты, софт и т.д.)
CREATE TABLE IF NOT EXISTS service_orders (
  id bigint generated by default as identity primary key,
  user_id bigint references app_users(id) ON DELETE CASCADE,
  user_email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  service_type text, -- 'Web', 'Mobile', 'AI', 'Consulting'
  project_name text,
  description text,
  contact_info text, -- Контакты для связи (Telegram, Phone)
  
  status text default 'pending', -- pending, in_progress, completed, cancelled
  
  -- Поля, заполняемые админом
  price text default '-', 
  eta timestamp with time zone, -- Оценочное время готовности
  completed_at timestamp with time zone
);

-- Отключаем RLS для простоты (как и в других таблицах)
ALTER TABLE service_orders DISABLE ROW LEVEL SECURITY;
