-- Run this in Supabase SQL Editor to enable SOS functionality

CREATE TABLE IF NOT EXISTS sos_tickets (
  id bigint generated by default as identity primary key,
  user_id bigint references app_users(id) ON DELETE CASCADE,
  user_email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  issue_type text,
  description text,
  urgency text,
  status text default 'pending', -- pending, in_progress, resolved, cancelled
  cost text default '-',
  solution text,
  is_paid boolean default false
);

-- Policy examples (if RLS is enabled):
-- ALTER TABLE sos_tickets ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Users can view own tickets" ON sos_tickets FOR SELECT USING (auth.uid() = user_id); 
-- Note: Since we are using custom auth (app_users table) instead of Supabase Auth, standard RLS won't work automatically without custom claims. 
-- Access control is handled at the application layer in this codebase.
