
-- ПОЛНЫЙ СКРИПТ НАСТРОЙКИ БАЗЫ ДАННЫХ BUNKER-255

-- 1. Таблица пользователей (app_users)
-- Используется вместо встроенной auth.users для упрощения демонстрации
CREATE TABLE IF NOT EXISTS app_users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text unique not null,
  password text not null, -- В демо хранится как есть. В продакшене нужно хешировать!
  role text default 'CLIENT', -- Варианты: 'CLIENT', 'ADMIN', 'OPERATOR'
  business_name text,
  subscriptions jsonb default '{}'::jsonb -- JSON для хранения флагов подписок (например, {"sos_business": true})
);

-- 2. Таблица заявок SOS (sos_tickets)
CREATE TABLE IF NOT EXISTS sos_tickets (
  id bigint generated by default as identity primary key,
  user_id bigint references app_users(id) ON DELETE CASCADE, -- Связь с таблицей пользователей
  user_email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  issue_type text,
  description text,
  urgency text,
  status text default 'pending', -- Варианты: pending, in_progress, resolved, cancelled
  cost text default '-',
  market_cost text default '-', -- Цена у конкурентов для сравнения
  solution text,
  is_paid boolean default false
);

-- 3. Таблица контактных форм (contact_requests)
CREATE TABLE IF NOT EXISTS contact_requests (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text,
  email text,
  type text,
  message text
);

-- 4. Создание администратора по умолчанию
-- Email: admin@bunker-255.com
-- Пароль: admin
INSERT INTO app_users (email, password, role, business_name, subscriptions)
VALUES (
    'admin@bunker-255.com', 
    'admin', 
    'ADMIN', 
    'HQ Command', 
    '{"sos_business": true}'::jsonb
)
ON CONFLICT (email) DO NOTHING;

-- 5. Отключение RLS (Row Level Security) для простоты
-- Внимание: В реальном приложении нужно настроить Policies, но для старта это позволит API работать сразу.
ALTER TABLE app_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE sos_tickets DISABLE ROW LEVEL SECURITY;
ALTER TABLE contact_requests DISABLE ROW LEVEL SECURITY;
